### ISSUE TITLE
Request to Remove Unauthorized Use of My Copyrighted Content

### ISSUE THREAD

**Issue by tszdabee** [rajatshetty982/Microstructure-analysis-on-steel#1]
Dear Rajat,

I have noticed that the README file from my GitHub repository (https://github.com/tszdabee/Charpy-Microstructure-Machine-Learning) has been copied and re-uploaded to your repository (https://github.com/rajatshetty982/Microstructure-analysis-on-steel) without my permission.

As the original author, I retain full copyright over this material, which has been shared with no license permitting redistribution. I kindly request that you remove the infringing content immediately.

If this issue is not resolved within 48 hours, I will escalate the matter to GitHub's DMCA takedown process.

Thank you for your cooperation.

Sincerely,
Tsz

**Comment by rajatshetty982** [comment]
You've got It wrong. The repo that you mentioned here has the readMe from
an ai chat bot. What you saw was a fork of your repo that i made, i wanted
to see how you've done things, and i didn't know much about GitHub then.
Sorry about that. I was researching for ideas for my final year projects.
I'll delete them, I had forgotten about those repos, as i became a backend
developer.
